### ISSUE TITLE
demo5 lack sample data file

### ISSUE THREAD

**Issue by woodgreat** [Xiaokang2022/tkintertools-demos#2]
演示5中没有数据文件，要用什么样的数据请添加一些，方便用户匹配，谢谢

**Comment by Xiaokang2022** [comment]
@woodgreat 演示 5 的数据文件有的，在文件夹 ./demos/demo5/images/ 中，使用时需一次性打开两张图

**Comment by woodgreat** [comment]
试了一下，通过了测试，5没有问题，只是说明不太明显
